{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "testchart.serviceAccountName" . }}
  labels:
{{ include "testchart.labels" . | indent 4 }}
{{- end -}}
